#!/usr/bin/python
#coding=utf-8
from PyQt4.QtGui import *
from PyQt4.QtCore import *
from ui.ui_mainwindow import *

class P2pMainWin( QMainWindow ):
	def __init__( self ):
		QMainWindow.__init__( self, parent=None )
		self.ui = Ui_MainWindow()
		self.ui.setupUi( self )
		self.createConnections()

	def openFiles( self ):
		print( 'You are trying to openFiles' )

	def createConnections( self ):
		self.connect( self.ui.fileOpenAction, SIGNAL('triggered()'),\
				self.openFiles )
	pass

def setDownLoadDir():
	pass

def readConfigFile( fullpath ):
	pass

import os
def createConfigFile( fullpath ):
	#todo test if exist config file
	f = open( fullpath+os.sep+'config', 'w' )
#todo replace \n with universal newlines
	f.writelines( '#DO NOT REMOVE THIS FILE\n' )
	f.writelines( '#不要删除这个文件!\n' )
	f.writelines( '#auto generated by the p2p app\n' )
	f.writelines( 'hashfile='+fullpath+os.sep+'hashfile\n' )
	#todo
	f.close()
	pass

config = {}
if 'nt' in os.name: #winXP or win7/8
	config['osprefix'] = '_'
else:
	config['osprefix'] = '.'
	pass

configFileFullPath = os.path.expanduser('~')+os.sep+config['osprefix']+'simpleP2p'
#todo
config['appDataPath'] = configFileFullPath
config['downloadPath'] = configFileFullPath+os.sep+'downloads'

'''
if os.path.isfile( configFileFullPath ):
	readConfigFile( configFileFullPath )
else:
	createConfigFile( configFileFullPath )
'''

import sys
app = QApplication( sys.argv )

myMainWin = P2pMainWin()
if not os.path.isdir( config['appDataPath'] ):
	os.mkdir( config['appDataPath'] )
	createConfigFile( config['appDataPath'] )
if not os.path.isdir( config['downloadPath'] ):
	os.mkdir( config['downloadPath'] )

myMainWin.show()

sys.exit( app.exec_() )

